version: "2.4"
services:
    jupyter:
        build:
            context: .
            dockerfile: ./docker/jupyter/Dockerfile 
        ports:
            - 8888:8888
        volumes:
            - ./:/home/jupyter
